version: "3"

services:

  gateway:
    image: nlepage/codyglot:base
    command: ["router", "gateway", "-e", "router:9090"]
    ports:
      - "8080"

  router:
    image: nlepage/codyglot:base
    command: ["router", "server", "-l", "golang:golang:9090"]
    expose:
      - "9090"

  golang:
    image: nlepage/codyglot:golang
    expose:
      - "9090"
