version: "3"

services:

  gateway:
    build: .
    image: nlepage/codyglot
    command: ["router", "gateway", "-e", "router:9090"]
    ports:
      - "8080"

  router:
    build: .
    image: nlepage/codyglot
    command: ["router", "server", "-l", "golang:golang:9090"]
    expose:
      - "9090"

  golang:
    build: .
    image: nlepage/codyglot
    command: ["executor", "golang"]
    expose:
      - "9090"
