version: "3"

services:

  repl:
    build: repl
    image: nlepage/codyglot:repl
    read_only: true
    ports:
      - "80"

  gateway:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    command: ["router", "gateway", "-e", "router:9090"]
    expose:
      - "8080"
  
  graphql:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    command: ["graphql", "--playground"]
    ports:
      - "8080"

  router:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    command: ["router", "server"]
    expose:
      - "9090"

  golang:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    tmpfs:
      - /tmp:exec
    command: ["executor", "golang", "--compiler-host", "compiler-golang"]
    expose:
      - "9090"
  
  compiler-golang:
    build: golang
    image: nlepage/codyglot:golang
    read_only: true
    tmpfs:
      - /tmp
    command: ["compiler", "golang"]
    expose:
      - "9090"

  nodejs:
    build: nodejs
    image: nlepage/codyglot:nodejs
    read_only: true
    tmpfs:
      - /tmp
    command: ["executor", "nodejs", "--compiler-host", "compiler-typescript"]
    expose:
      - "9090"

  compiler-typescript:
    build: nodejs
    image: nlepage/codyglot:nodejs
    read_only: true
    tmpfs:
      - /tmp
    command: ["compiler", "typescript"]
    expose:
      - "9090"

  filestore:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    volumes:
      - /var/codyglot/filestore
    command: ["filestore", "server"]
    expose:
      - "9090"
