version: "3"

services:

  repl:
    build: repl
    image: nlepage/codyglot:repl
    ports:
      - "80"

  gateway:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    command: ["router", "gateway", "-e", "router:9090"]
    expose:
      - "8080"

  router:
    build: .
    image: nlepage/codyglot:base
    read_only: true
    command: ["router", "server"]
    expose:
      - "9090"

  golang:
    build: executor/golang
    image: nlepage/codyglot:golang
    read_only: true
    tmpfs:
      - /tmp:exec
    expose:
      - "9090"

  nodejs:
    build: executor/nodejs
    image: nlepage/codyglot:nodejs
    read_only: true
    tmpfs:
      - /tmp
    expose:
      - "9090"
