apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: golang
spec:
  template:
    metadata:
      labels:
        app: codyglot
        service: executor
        language: golang
    spec:
      containers:
        - image: nlepage/codyglot:golang
          name: golang
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: golang
spec:
  selector:
    app: codyglot
    service: executor
    language: golang
  ports:
    - port: 9090
