apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  template:
    metadata:
      labels:
        app: codyglot
        tier: backend
    spec:
      containers:
        - image: nlepage/codyglot:nodejs
          name: nodejs
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: codyglot
    tier: backend
  ports:
    - port: 9090
