apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-commander
spec:
  template:
    metadata:
      labels:
        app: codyglot
        service: redis-commander
    spec:
      containers:
        - image: rediscommander/redis-commander
          name: redis-commander
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  selector:
    app: codyglot
    service: redis-commander
  ports:
    - port: 8081
  type: NodePort