apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: repl
spec:
  template:
    metadata:
      labels:
        app: codyglot
        tier: frontend
    spec:
      containers:
        - image: nlepage/codyglot:repl
          name: repl
---
apiVersion: v1
kind: Service
metadata:
  name: repl
spec:
  selector:
    app: codyglot
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
