// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CommandResult struct {
	Status   int    `json:"status"`
	Stdout   string `json:"stdout"`
	Stderr   string `json:"stderr"`
	Duration int    `json:"duration"`
}

type ExecuteResponse struct {
	Compilation *CommandResult   `json:"compilation"`
	Executions  []*CommandResult `json:"executions"`
}

type ExecutionInput struct {
	Stdin string `json:"stdin"`
}

type FileInput struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}
