// Code generated by protoc-gen-go. DO NOT EDIT.
// source: executor.proto

/*
Package executor is a generated protocol buffer package.

It is generated from these files:
	executor.proto

It has these top-level messages:
	ExecuteRequest
	ExecuteResponse
*/
package executor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExecuteRequest struct {
	Code  string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	StdIn []byte `protobuf:"bytes,2,opt,name=stdIn,proto3" json:"stdIn,omitempty"`
}

func (m *ExecuteRequest) Reset()                    { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()               {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExecuteRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ExecuteRequest) GetStdIn() []byte {
	if m != nil {
		return m.StdIn
	}
	return nil
}

type ExecuteResponse struct {
	ExitCode uint32 `protobuf:"varint,1,opt,name=exitCode" json:"exitCode,omitempty"`
	StdOut   []byte `protobuf:"bytes,2,opt,name=stdOut,proto3" json:"stdOut,omitempty"`
	StdErr   []byte `protobuf:"bytes,3,opt,name=stdErr,proto3" json:"stdErr,omitempty"`
}

func (m *ExecuteResponse) Reset()                    { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()               {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExecuteResponse) GetExitCode() uint32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *ExecuteResponse) GetStdOut() []byte {
	if m != nil {
		return m.StdOut
	}
	return nil
}

func (m *ExecuteResponse) GetStdErr() []byte {
	if m != nil {
		return m.StdErr
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecuteRequest)(nil), "com.github.zenika.codyglot.executor.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "com.github.zenika.codyglot.executor.ExecuteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Executor service

type ExecutorClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type executorClient struct {
	cc *grpc.ClientConn
}

func NewExecutorClient(cc *grpc.ClientConn) ExecutorClient {
	return &executorClient{cc}
}

func (c *executorClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := grpc.Invoke(ctx, "/com.github.zenika.codyglot.executor.Executor/execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Executor service

type ExecutorServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

func RegisterExecutorServer(s *grpc.Server, srv ExecutorServer) {
	s.RegisterService(&_Executor_serviceDesc, srv)
}

func _Executor_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.zenika.codyglot.executor.Executor/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Executor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.zenika.codyglot.executor.Executor",
	HandlerType: (*ExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "execute",
			Handler:    _Executor_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executor.proto",
}

func init() { proto.RegisterFile("executor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xad, 0x48, 0x4d,
	0x2e, 0x2d, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x4e, 0xce, 0xcf, 0xd5,
	0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0xab, 0x4a, 0xcd, 0xcb, 0xcc, 0x4e, 0xd4, 0x4b, 0xce,
	0x4f, 0xa9, 0x4c, 0xcf, 0xc9, 0x2f, 0xd1, 0x83, 0x29, 0x55, 0xb2, 0xe2, 0xe2, 0x73, 0x05, 0xb3,
	0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xe2, 0x92, 0x14,
	0xcf, 0x3c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47, 0x29, 0x96, 0x8b, 0x1f, 0xae,
	0xb7, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8a, 0x8b, 0x23, 0xb5, 0x22, 0xb3, 0xc4, 0x19,
	0x66, 0x00, 0x6f, 0x10, 0x9c, 0x2f, 0x24, 0xc6, 0xc5, 0x56, 0x5c, 0x92, 0xe2, 0x5f, 0x5a, 0x02,
	0x35, 0x05, 0xca, 0x83, 0x8a, 0xbb, 0x16, 0x15, 0x49, 0x30, 0xc3, 0xc5, 0x5d, 0x8b, 0x8a, 0x8c,
	0x9a, 0x18, 0xb9, 0x38, 0x5c, 0xa1, 0xee, 0x14, 0x2a, 0xe3, 0x62, 0x87, 0xb8, 0x39, 0x55, 0xc8,
	0x58, 0x8f, 0x08, 0x8f, 0xe9, 0xa1, 0xfa, 0x4a, 0xca, 0x84, 0x34, 0x4d, 0x10, 0xef, 0x28, 0x31,
	0x38, 0x71, 0x45, 0x71, 0xc0, 0x64, 0x93, 0xd8, 0xc0, 0xe1, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x13, 0xee, 0x92, 0x23, 0x69, 0x01, 0x00, 0x00,
}
